# version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TuPasswordSeguro123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiBaseDeDatos;User=sa;Password=TuPasswordSeguro123!;TrustServerCertificate=true;

      # --- AÑADIR ESTAS 3 LÍNEAS AQUÍ ---
      - AdminUser__Email=admin@pos.com
      - AdminUser__Password=Admin12345 # ¡IMPORTANTE! Cambia esto por una contraseña segura y diferente a la de la BD
      - AdminUser__Username=admin
      # --- FIN DE LÍNEAS A AÑADIR ---

      # --- AÑADIR ESTAS 3 LÍNEAS PARA EL TOKEN ---
      - Jwt__Key=ESTA_ES_MI_CLAVE_SECRETA_SUPER_LARGA_Y_SEGURA_PARA_PRODUCCION_CAMBIAME
      - Jwt__Issuer=https://tu-dominio.com
      - Jwt__Audience=https://tu-dominio.com
      # --- FIN DE LÍNEAS A AÑADIR ---

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlserver_data: