services:
  frontend:
    # --- INICIO DE CAMBIOS ---
    build:
      context: ./frontend
      target: build # Le dice a Docker que use la etapa "build" del Dockerfile
    
    ports:
      - "5001:4200" # Mapea al puerto de ng serve
    # --- FIN DE CAMBIOS ---
      
    # ---- LÍNEA MODIFICADA ----
    command: npm run start -- --host 0.0.0.0 --poll 1000
    # --------------------------
    
    volumes:
      - ./frontend:/app
      - /app/node_modules